### ISSUE TITLE
Bot produces "None" messages on network errors

### ISSUE THREAD

**Issue by CrsiX** [hopfenspace/MateBot#52]
When the Telegram API seems to be down or the network is unreachable, the bot can't send messages. It raises an OSError internally. This is catched and the bot tries to send a message to the developers via Telegram, which will fail again - obviously. But this second attempt produces the message `NoneType: None` and sends it to the chat the previous call failed in. This behavior is not expected!

**Comment by CrsiX** [comment]
1bf4b7b2c870db675af7b19f1d47aca63d11c278 should fix this problem. But currently, this feature has not yet been checked, so we can't tell if it's working.

**Comment by CrsiX** [comment]
We've seen some of those messages again. The only thing the syslog can tell is something like this:

    Sep 29 23:04:49 MateBotDev matebot 24400: ERROR: mate_bot.err: Something raised an unhandled exception, it will be sent to the developers

The origin of this log message is [here](https://github.com/CrsiX/MateBot/blob/9799bd764d3a0e6e62a869bc83cf637cc3b6284a/mate_bot/err.py#L71-L72). However, we don't know what happened before.

**Comment by CrsiX** [comment]
Even after extending the information... No better clue:

```Something raised an unhandled exception, it will be sent to the developers: (None, None, None) / NoneType: None```

**Comment by CrsiX** [comment]
It looks like the error handler gets called without an exception, therefore the exception is `None`...

**Comment by CrsiX** [comment]
After introducing 2908e8caf27775fe4e7b1aca1c22c6726e6f7cfe, I was able to reproduce the bug. The log file contains the following lines:

```
matebot 14054: WARNING: telegram.vendor.ptb_urllib3.urllib3.connectionpool: Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f4591d2d978>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot[TOKEN]/getUpdates
matebot 14054: WARNING: telegram.vendor.ptb_urllib3.urllib3.connectionpool: Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f45904c3b38>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot[TOKEN]/getUpdates
matebot 14054: WARNING: telegram.vendor.ptb_urllib3.urllib3.connectionpool: Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f45904c3ac8>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /bot[TOKEN]/getUpdates
matebot 14054: ERROR: telegram.ext.updater: Error while getting Updates: urllib3 HTTPError HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot[TOKEN]/getUpdates (Caused by NewConnectionError('<telegram.vendor.ptb_urllib3.urllib3.connection.VerifiedHTTPSConnection object at 0x7f45904c3ef0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

Due to this network error, the exception is `None`, because there was no exception at all. This means, that the error handler will also be called on network errors.
Note that the parameter `update` seems to be `None` as well because the network error above produces an AttributeError in the error handler:

```
matebot 14054: ERROR: telegram.ext.dispatcher: An uncaught error was raised while handling the error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/dispatcher.py", line 326, in process_update
    self.dispatch_error(None, update)
  File "/usr/local/lib/python3.7/dist-packages/telegram/ext/dispatcher.py", line 522, in dispatch_error
    callback(update, CallbackContext.from_error(update, error, self))
  File "/home/matebot/MateBot/mate_bot/err.py", line 121, in log_error
    f"Extended debug information:\n```\n{_json.dumps(update.to_dict(), indent=2, sort_keys=True)}```"
AttributeError: 'NoneType' object has no attribute 'to_dict'
```

**Comment by CrsiX** [comment]
34510d791e475c56877fcb1f03b50088fd741b2a should fix this issue now by ignoring all calls of the error handler that have no attached exception. I will now wait until I can confirm this works.

**Comment by CrsiX** [comment]
It looks like the error was fixed with this commit. I will close this issue.
